/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './features/student/routes/wallet'
import { Route as SubscriptionsRouteImport } from './features/student/routes/subscriptions'
import { Route as DocumentsRouteImport } from './features/student/routes/documents'
import { Route as AuthRouteImport } from './features/auth/routes/auth'
import { Route as LecturerRouteRouteImport } from './features/lecturer/routes/route'
import { Route as AdminRouteRouteImport } from './features/admin/routes/route'
import { Route as IndexRouteImport } from './features/student/routes/index'
import { Route as WalletDotcheckoutRouteImport } from './features/student/routes/wallet.checkout'
import { Route as LecturerDocumentsRouteImport } from './features/lecturer/routes/documents'
import { Route as AdminUsersRouteImport } from './features/admin/routes/users'
import { Route as AdminSubscriptionsRouteImport } from './features/admin/routes/subscriptions'
import { Route as AdminSubjectsRouteImport } from './features/admin/routes/subjects'
import { Route as AdminRolesRouteImport } from './features/admin/routes/roles'
import { Route as AdminLecturersRouteImport } from './features/admin/routes/lecturers'
import { Route as AdminAiConfigRouteImport } from './features/admin/routes/ai-config'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerRouteRoute = LecturerRouteRouteImport.update({
  id: '/lecturer',
  path: '/lecturer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletDotcheckoutRoute = WalletDotcheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => WalletRoute,
} as any)
const LecturerDocumentsRoute = LecturerDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => LecturerRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLecturersRoute = AdminLecturersRouteImport.update({
  id: '/lecturers',
  path: '/lecturers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAiConfigRoute = AdminAiConfigRouteImport.update({
  id: '/ai-config',
  path: '/ai-config',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/lecturer': typeof LecturerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/admin/ai-config': typeof AdminAiConfigRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lecturer/documents': typeof LecturerDocumentsRoute
  '/wallet/checkout': typeof WalletDotcheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/lecturer': typeof LecturerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/admin/ai-config': typeof AdminAiConfigRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lecturer/documents': typeof LecturerDocumentsRoute
  '/wallet/checkout': typeof WalletDotcheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/lecturer': typeof LecturerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/admin/ai-config': typeof AdminAiConfigRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lecturer/documents': typeof LecturerDocumentsRoute
  '/wallet/checkout': typeof WalletDotcheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/lecturer'
    | '/auth'
    | '/documents'
    | '/subscriptions'
    | '/wallet'
    | '/admin/ai-config'
    | '/admin/lecturers'
    | '/admin/roles'
    | '/admin/subjects'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/lecturer/documents'
    | '/wallet/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/lecturer'
    | '/auth'
    | '/documents'
    | '/subscriptions'
    | '/wallet'
    | '/admin/ai-config'
    | '/admin/lecturers'
    | '/admin/roles'
    | '/admin/subjects'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/lecturer/documents'
    | '/wallet/checkout'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/lecturer'
    | '/auth'
    | '/documents'
    | '/subscriptions'
    | '/wallet'
    | '/admin/ai-config'
    | '/admin/lecturers'
    | '/admin/roles'
    | '/admin/subjects'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/lecturer/documents'
    | '/wallet/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LecturerRouteRoute: typeof LecturerRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocumentsRoute: typeof DocumentsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  WalletRoute: typeof WalletRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer': {
      id: '/lecturer'
      path: '/lecturer'
      fullPath: '/lecturer'
      preLoaderRoute: typeof LecturerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/checkout': {
      id: '/wallet/checkout'
      path: '/checkout'
      fullPath: '/wallet/checkout'
      preLoaderRoute: typeof WalletDotcheckoutRouteImport
      parentRoute: typeof WalletRoute
    }
    '/lecturer/documents': {
      id: '/lecturer/documents'
      path: '/documents'
      fullPath: '/lecturer/documents'
      preLoaderRoute: typeof LecturerDocumentsRouteImport
      parentRoute: typeof LecturerRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lecturers': {
      id: '/admin/lecturers'
      path: '/lecturers'
      fullPath: '/admin/lecturers'
      preLoaderRoute: typeof AdminLecturersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ai-config': {
      id: '/admin/ai-config'
      path: '/ai-config'
      fullPath: '/admin/ai-config'
      preLoaderRoute: typeof AdminAiConfigRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAiConfigRoute: typeof AdminAiConfigRoute
  AdminLecturersRoute: typeof AdminLecturersRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAiConfigRoute: AdminAiConfigRoute,
  AdminLecturersRoute: AdminLecturersRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface LecturerRouteRouteChildren {
  LecturerDocumentsRoute: typeof LecturerDocumentsRoute
}

const LecturerRouteRouteChildren: LecturerRouteRouteChildren = {
  LecturerDocumentsRoute: LecturerDocumentsRoute,
}

const LecturerRouteRouteWithChildren = LecturerRouteRoute._addFileChildren(
  LecturerRouteRouteChildren,
)

interface WalletRouteChildren {
  WalletDotcheckoutRoute: typeof WalletDotcheckoutRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletDotcheckoutRoute: WalletDotcheckoutRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LecturerRouteRoute: LecturerRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DocumentsRoute: DocumentsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  WalletRoute: WalletRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
